# Assignment_1

In [2]:
import numpy as np
import pandas as pd

# 1.GRADED

a)Using a for loop, iterate through the list x and print an item if its divisible by 2 and less than 6


In [2]:
#creating a list x.
x=[1,2,3,4,5,6,7,8,9,10]

for i in x:
    if((i % 2 == 0) and (i<6)):
        print(i)


2
4


(b) Using a for loop, iterate through the dictionary y and print a single string of the form "company, ceo"


In [5]:
y = {'Satya Nadella': 'Microsoft',
     'Jeff Bezos': 'Amazon',
     'Tim Cook': 'Apple'
    }

for ceo, company in y.items():
    print("CEO:",company+", Name:",ceo)

CEO: Microsoft, Name: Satya Nadella
CEO: Amazon, Name: Jeff Bezos
CEO: Apple, Name: Tim Cook


# 2.GRADED

 (a) Complete sub_numbers so that it return difference of two numbers


In [13]:
def sub_numbers(a,b):
    return a-b

x = int(input('enter 1st number which you want to subtract:'))
y = int(input('enter 2nd number which you want to subtract:'))

print(sub_numbers(x,y))

enter two number which you want to subtract:4
enter two number which you want to subtract:2
2


 (b) Write a function called mult_numbers to multiply two numbers

In [17]:
def mult_numbers(a,b):
    return a*b

a,b = map(int,input('enter the the numbers which you want to multiply:').split())

mult_numbers(a,b)

enter the the numbers which you want to multiply:4 5


20

# 3. GRADED

 (a) Determine the shape, number of dimensions and type of elements in the numpy array arr

In [27]:
#let,create numpy array of size (3,5)

arr = np.arange(15).reshape(3, 5)

print('array:\n',arr)
print('\n')
print('shape of array: ',arr.shape)
print('\n')
print('no. fo dimensions in array:',arr.ndim)
print('\n')
print('type of elements in array:',arr.dtype)

array:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


shape of array:  (3, 5)


no. fo dimensions in array: 2


type of elements in array: int32


 (b) Determine the sum of elements in arr

In [30]:
print(np.sum(arr))

105


 (c) Determine the mean of elements in arr

In [31]:
print(np.mean(arr))

7.0


(d) Create an array of the same shape as arr but filled with zeros

In [35]:
print(np.zeros(arr.shape , dtype=int))

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [ ]:
(e) Create an array of the same shape as arr but filled with ones

In [36]:
print(np.ones(arr.shape , dtype = int))

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


(f) Create an array of the same shape as arr but where all elements are squared
values

In [38]:
print(np.square(arr))

[[  0   1   4   9  16]
 [ 25  36  49  64  81]
 [100 121 144 169 196]]


(g) Create an array result of shape 3*3 resulting from multiplication of arr with
transpose(arr)

In [41]:
print(np.dot(arr,arr.T))

[[ 30  80 130]
 [ 80 255 430]
 [130 430 730]]


# 4.GRADED

In [27]:
df = pd.read_csv('https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv')
df.head(10)

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa
5           5.4          3.9           1.7          0.4  setosa
6           4.6          3.4           1.4          0.3  setosa
7           5.0          3.4           1.5          0.2  setosa
8           4.4          2.9           1.4          0.2  setosa
9           4.9          3.1           1.5          0.1  setosa

(a) Determine the shape of the dataframe

In [13]:
print(df.shape)

(150, 5)


 (b) Print out all the columns of the dataframe
 

In [14]:
print(df.columns)

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')


(c) Print the 3rd element of the dataframe


In [15]:
print(df.iloc[2])

sepal_length       4.7
sepal_width        3.2
petal_length       1.3
petal_width        0.2
species         setosa
Name: 2, dtype: object


 (d) Find the average of 'petal_width' where species is 'virginica'


In [23]:
print(df.loc[df["species"] == 'virginica','petal_width'].mean())

2.0260000000000002


(e) Find the maximum of 'sepal_width' where species is 'setosa'


In [22]:
print(max(df.loc[df["species"] == 'setosa','sepal_width']))

4.4


(f): What is the average value of sepal_length

In [24]:
print(df['sepal_length'].mean())

5.843333333333334


(g): What is the maximum value of sepal_width


In [25]:
print(df['sepal_width'].max())

4.4


 (h): What is the minimum value of petal_width


In [26]:
print(df['petal_width'].min())

0.1
